### ISSUE TITLE
Multiprocessing/Threading

### ISSUE THREAD

**Issue by mez0cc** [mez0cc/beagle#5]
This implementation is quite slow, it needs multiprocessing or threading.

Edit: This is desired for host discovery and enumeration.

**Comment by AlexanderBodnya** [comment]
Hey,

I want to commit, but I am unable to create branches on your project. Could you please give me access?

**Comment by mez0cc** [comment]
Hey, 

I don't know if its me being special, but I'm getting:
```
> # ./smbeagle.py                                                                                                                                                                    [±master ●]
Traceback (most recent call last):
  File "./smbeagle.py", line 31, in <module>
    args = parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 2010, in _parse_known_args
    ', '.join(required_actions))
  File "/usr/lib/python3.6/argparse.py", line 2400, in error
    self.print_usage(_sys.stderr)
  File "/usr/lib/python3.6/argparse.py", line 2370, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/lib/python3.6/argparse.py", line 2336, in format_usage
    return formatter.format_help()
  File "/usr/lib/python3.6/argparse.py", line 291, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.6/argparse.py", line 222, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 346, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
```

Apparently its something to do with the formatting of the args?

**Comment by mez0cc** [comment]
The above issue was to do with the implementation of `metavar` within arguments.

**Comment by AlexanderBodnya** [comment]
By documentation metavar is optional, so maybe you should remove it completely? It is empty for every argument, so should make no difference. 
P. s. Sorry it took me long time to reply, day job is time consuming. You can expect me checking on the repo and issues during the weekend/holidays
